csharp/ColumnDescriptor.cs
csharp/IColumnDescriptorVisitor.cs
csharp/LogicalColumnReader.cs
csharp/LogicalColumnStream.cs
csharp/LogicalColumnWriter.cs
csharp/LogicalRead.cs
csharp/LogicalWrite.cs
csharp/ParquetSharp.csproj

Added IColumnDescriptorVisitor. This can be used to get the column types before having a logical reader or writer.
Minor renaming.
Bumped next release version to beta10.

Added IColumnDescriptorVisitor.

---

csharp/ParquetSharp.csproj

Nuget package has been published. Need to tag after this merge.

It's time to get out of beta.

---

csharp.test/TestColumn.cs
csharp.test/TestDecimal.cs
csharp.test/TestLogicalTypeRoundtrip.cs
csharp/Column.cs
csharp/ColumnDescriptor.cs
csharp/Decimal.cs
csharp/FixedLenByteArray.cs
csharp/InternalsVisibleTo.cs
csharp/LogicalColumnReader.cs
csharp/LogicalColumnWriter.cs
csharp/LogicalRead.cs
csharp/LogicalWrite.cs
csharp/Schema/DecimalMetadata.cs
csharp/Schema/PrimitiveNode.cs

Added Column.IsSupported() to check for C# type support.
Added C# decimal support, currently only full precision is support (96-bits).

Added 96-bits Decimal support.

---

csharp.test/TestColumnReader.cs
csharp/ColumnReader.cs

Make Skip an abstract method on ColumnReader

---

csharp.test/TestNode.cs
csharp/Schema/DecimalMetadata.cs
csharp/Schema/GroupNode.cs
csharp/Schema/Node.cs
csharp/Schema/PrimitiveNode.cs

Implement deep cloning and equality for nodes

---

cpp/ResizableBuffer.cpp
csharp/ExceptionInfo.cs
csharp/IO/ResizableBuffer.cs

https://github.com/G-Research/ParquetSharp/issues/50

Expose initial size for resizable buffer

---

csharp/ParquetSharp.targets

Ensure copy works for non-net461 framework versions

Use TargetFrameworkIdentifier not TargetFramework

---

csharp.test/TestLogicalTypeRoundtrip.cs
csharp/ParquetSharp.csproj

Improve min/max tests for decimal

---

cpp/CMakeLists.txt
cpp/ExceptionInfo.h
cpp/ManagedOutputStream.cpp
cpp/ManagedRandomAccessFile.cpp
csharp.test/ParquetSharp.Test.csproj
csharp.test/Program.cs
csharp.test/TestManagedRandomAccessFile.cs
csharp.test/TestParquetFileReader.cs
csharp.test/TestParquetPerformance.cs
csharp/IO/BufferReader.cs
csharp/IO/ManagedOutputStream.cs
csharp/IO/ManagedRandomAccessFile.cs
csharp/IO/OutputStream.cs
csharp/IO/RandomAccessFile.cs
csharp/ParquetSharp.csproj
vcpkg_linux.sh
vcpkg_windows.bat

Adds ManagedRandomAccessFile and ManagedOutputStream, implementations of
the RandomAccessFile and OutputStream C++ interfaces that call back into
C# to read/write to a .Net IO.Stream.

Added managed streams support in IO classes.

---

cpp/ManagedOutputStream.cpp
cpp/ManagedRandomAccessFile.cpp
csharp.test/TestManagedRandomAccessFile.cs
csharp/IO/ManagedOutputStream.cs
csharp/IO/ManagedRandomAccessFile.cs

If there we're no managed reference left to a ManagedOutputStream or ManagedRandomAccessFile the class (and all it's delegates) could be collected while there was still a native reference to it from the C++ ParquetFileReader or ParquetFileWriter.
This PR adds a GCHandle to both managed class that keeps them alive until Free is called, which is then called by the C++ destructor.

Fix a use after free bug

---

cmake/FindBZip2.cmake
cmake/FindOpenSSL.cmake
cpp/BufferOutputStream.cpp
cpp/CMakeLists.txt
cpp/ManagedOutputStream.cpp
cpp/ManagedRandomAccessFile.cpp
cpp/ParquetFileWriter.cpp
csharp.test/TestParquetFileReader.cs
vcpkg_windows.bat

Get the library compiling again when building against Arrow 0.16.

Initial upgrade to Arrow 0.16

---

cpp/CMakeLists.txt
cpp/ColumnChunkMetaData.cpp
cpp/ColumnCryptoMetaData.cpp
csharp.test/ParquetSharp.Test.csproj
csharp.test/TestEncryption.cs
csharp/ColumnChunkMetaData.cs
csharp/ColumnCryptoMetaData.cs
csharp/Schema/ColumnPath.cs

Updated to .NET Core 3.1 and C# 8.0 for unit tests (main project still on C# 7.3).
Updated nuget dependencies.

Added API support for ColumnCryptoMetaData.

---

README.md
cpp/ParquetFileReader.cpp
cpp/ParquetFileWriter.cpp
csharp.test/Program.cs
csharp.test/TestAadPrefixVerifier.cs
csharp.test/TestBuffer.cs
csharp.test/TestColumn.cs
csharp.test/TestColumnPath.cs
csharp.test/TestColumnReader.cs
csharp.test/TestColumnWriter.cs
csharp.test/TestDecimal128.cs
csharp.test/TestDerivedKeyRetriever.cs
csharp.test/TestLogicalTypeRoundtrip.cs
csharp.test/TestManagedRandomAccessFile.cs
csharp.test/TestParquetFileReader.cs
csharp.test/TestParquetFileWriter.cs
csharp.test/TestParquetPerformance.cs
csharp.test/TestPhysicalTypeRoundtrip.cs
csharp.test/TestRowOrientedParquetFile.cs
csharp/ColumnWriter.cs
csharp/ParquetFileReader.cs
csharp/ParquetFileWriter.cs
csharp/RowGroupWriter.cs
csharp/RowOriented/ParquetRowWriter.cs

Mitigates Issue  #104, expect user to have to call Close().

Update Dispose() logic of writers to match the C++ API behaviour

---

README.md
csharp.test/TestRowOrientedParquetFile.cs
csharp/RowOriented/MapToColumn.cs
csharp/RowOriented/ParquetFile.cs
csharp/RowOriented/ParquetRowReader.cs

This is my attempt to address my own issue #90 
I could add more testing if necessary to verify the various exceptions are thrown to enforce proper attribute usage.

support for mapping fields by name (RowOriented)

---

csharp.test/LogicalValueSetter.cs
csharp.test/PhysicalValueSetter.cs
csharp.test/TestBuffer.cs
csharp.test/TestColumnReader.cs
csharp.test/TestColumnWriter.cs
csharp.test/TestDecimal128.cs
csharp.test/TestLogicalTypeRoundtrip.cs
csharp.test/TestManagedRandomAccessFile.cs
csharp.test/TestParquetFileReader.cs
csharp.test/TestParquetFileWriter.cs
csharp.test/TestParquetPerformance.cs
csharp.test/TestPhysicalTypeRoundtrip.cs
csharp/ColumnWriter.cs

Add unit tests for Buffered row groups.

---

CMakeLists.txt
vcpkg_linux.sh
vcpkg_windows.bat

Generate a smaller .so shared library file on Linux.

---

.github/workflows/ci.yml
vcpkg_linux.sh
vcpkg_version.txt
vcpkg_windows.bat

This will allow to use a fork if the need arises

Make the vcpkg URL configurable

---

vcpkg_linux.sh
vcpkg_windows.bat

Disable vcpkg debug build in CI

---

README.md

Note: we should also update the project description to be in line with the README.

Update README to highlight supported platforms

---

csharp.test/Program.cs
csharp.test/TestLogicalTypeRoundtrip.cs
csharp/Column.cs
csharp/ColumnDescriptor.cs
csharp/LogicalRead.cs
csharp/LogicalWrite.cs

Refactor LogicalRead and LogicalWrite per-element conversion to reduce code duplication.

Add support for UUID logical type.

---

.github/workflows/ci.yml
build_unix.sh
build_windows.bat
cpp/FileMetaData.cpp
cpp/ParquetFileReader.cpp
cpp/ParquetFileWriter.cpp
csharp.test/TestLogicalTypeRoundtrip.cs
csharp/FileMetaData.cs
csharp/ParquetSharp.csproj
vcpkg_unix.sh
vcpkg_version.txt
vcpkg_windows.bat

Build against arrow-3.0.0.
Fix minor compilation issues.

Update to arrow-3.0.0

---

cpp/CMakeLists.txt
cpp/MemoryPool.cpp
csharp.test/Program.cs
csharp.test/TestMemoryLeaks.cs
csharp.test/TestMemoryPool.cs
csharp/ExceptionInfo.cs
csharp/MemoryPool.cs

Add basic memory leak detection tests.

Expose Arrow default memory pool properties.

---

cpp/KeyValueMetadata.cpp
cpp/ParquetFileWriter.cpp
csharp.test/Program.cs
csharp.test/TestParquetFileWriter.cs
csharp.test/TestRowOrientedParquetFile.cs
csharp/ParquetFileWriter.cs
csharp/RowOriented/ParquetRowWriter.cs

Expose more ParquetFileWriter properties to C#.

---

cpp/Node.cpp
csharp/Schema/GroupNode.cs
csharp/Schema/Node.cs
csharp/Schema/PrimitiveNode.cs

This should partially help with Issue #175.

Add native call for Schema.Node.Equals() instead of using made up C# implementation.

---

README.md

Clarifies processor architecture as discussed in #197 .

added note on x64 to readme

---

.github/workflows/ci.yml

https://github.com/dotnet/sdk/issues/11639

Try to fix random segfault under Ubuntu 18.04 CI

---

csharp.test/TestColumn.cs
csharp.test/TestLogicalTypeFactory.cs
csharp/LogicalTypeFactory.cs

Add isSupportedType method back in LogicalTypeFactory

---

csharp/ParquetSharp.csproj

This is a prerequisite to release version `5.0.0-beta2`

Bump version to 5.0.0-beta2

---

README.md

Addresses #239, cc @gitfvb, thank you, let me know if you're happy with the wording!

Add documentation on how to use ParquetSharp from PowerShell

---

csharp.benchmark/FloatTimeSeriesWrite.cs
csharp.test/TestRowOrientedParquetFile.cs
csharp/RowOriented/ParquetRowWriter.cs

This method improves performance by reducing the number of allocations needed. In the new benchmark added I see a 25% speed up.

Add WriteRowSpan method to ParquetRowWriter

---

.github/workflows/ci.yml
csharp.test/ParquetSharp.Test.csproj
fsharp.test/ParquetSharp.Test.FSharp.fsproj

CI workflow without worning - https://github.com/ljubon/ParquetSharp/actions/runs/5801944212/job/15727971495

fix ci warnings

---

.github/ISSUE_TEMPLATE/bug_report.yml

adding an issue template for reporting bugs, including the following inputs:
- Issue Description
- Environment Information (ParquetSharp Version, .NET Framework/SDK Version, OS)
- Steps To Reproduce
- Expected Behavior
- Screenshots (Optional)
- Additional Context (Optional)

add ISSUE_TEMPLATE: Bug Report Form

---

.github/ISSUE_TEMPLATE/feature_request.yml

Adding an issue template for requesting features, including the following inputs:
- Related problem
- Suggested solution/implementation
- Alternatives (optional)
- Additional context (optional)

add ISSUE_TEMPLATE: feature request

---

csharp.test/TestRowOrientedParquetFile.cs

Just a minor cleanup, getting familiar with the project :-)

TestWriterDoubleDispose: remove outdated comment

---

docs/PowerShell.md

This is another PR for enhancing the available documentation. I felt that the PowerShell guide could use some improvements to reduce friction for new users, so I simplified the installation and basic usage steps. This guide still assumes that the user is familiar with PowerShell scripting.  
Feel free to make any changes as required.
- Clarified installation steps using nuget (for Windows users specifically)
- Added extra requirements for scripts to execute (editing versions, selecting architecture)
- Required for `Copy-Item` snippets to work correctly
- Added reminder for user to change the version/architecture
- Added basic powershell usage: loading `ParquetSharp.dll` and getting a reference to a `ParquetFileReader`
- Lists the previous example script if user wants more advanced …

Enhance PowerShell documentation

---

README.md

Hi, this is a PR for some more documentation enhancements related to potential issues users may encounter when building locally.
I went through the manual build process myself and I hit quite a few roadblocks which might cause friction for new users, especially relating to having all the available Visual Studio modules installed in order to run the build script.
This is not a comprehensive troubleshooting guide, but it aims to solve some of the errors that may come up after running the script (which may not entirely obvious, as they do occur even after installing the required C++ tools).
Please let me know if there's any other changes you would like to see, or if you would prefer if this troubleshooting section were in another file in the `docs`, rather than to expand the README.
- Added …

Document potential build issues in README

---

csharp/ParquetSharp.csproj

Bump the version so we can release the bug fix from #436. I think this should be the final beta before we release 15.0.2

Bump version to 15.0.2-beta2

---

csharp.test/TestLogicalTypeFactory.cs
csharp/ColumnDescriptor.cs

Fix handling reference types that don't inherit directly from object

---

csharp/ParquetSharp.csproj

#450 Removed System.Memory from Net 6+

---

.github/workflows/check-required.yml

This PR replaces the script with the common action

Add check required action in place of the script

---

csharp.test/TestLogicalTypeRoundtrip.cs
csharp/LogicalTypeFactory.cs

Support writing required byte arrays
