G-Research/ParquetSharp

- csharp.test/LogicalColumnReaderToArray.cs
- csharp.test/ParquetSharp.Test.csproj
- csharp.test/TestColumnWriter.cs
- csharp.test/TestDecimal128.cs
- csharp.test/TestLogicalTypeRoundtrip.cs
- csharp.test/TestParquetPerformance.cs
- csharp/ColumnWriter.cs
- csharp/LogicalColumnReader.cs
- csharp/LogicalColumnWriter.cs
- csharp/RowOriented/ParquetRowWriter.cs
* Added test for ColumnWriter.WriteBatch() with optional values.
Fixed precondition check.
* Added Span and ReadOnlySpan overload to LogicalColumnReader/Writer.
* Removed old API usage.
* Added IEnumerable<TElement> interface to LogicalColumnReader.
Upgraded nuget dependencies.
> Spans, IEnumerable and minor fixes.

- csharp.test/TestColumn.cs
- csharp.test/TestColumnWriter.cs
- csharp.test/TestLogicalTypeRoundtrip.cs
- csharp/Column.cs
- csharp/ParquetSharp.csproj
Bumped release version to 1.4.0.3.
Fixed regression of not throwing exception on unsupported column types.
Simplified TestBigArrayRoundtrip().
> Fixed regression of not throwing exception on unsupported column types

- .gitattributes
- cpp/BufferOutputStream.cpp
- csharp.test/TestBuffer.cs
- csharp.test/TestLogicalTypeRoundtrip.cs
- csharp.test/TestRowOrientedParquetFile.cs
- csharp/IO/BufferOutputStream.cs
- csharp/LogicalRead.cs
- csharp/ParquetSharp.csproj
- csharp/RowOriented/ParquetDecimalScale.cs
- csharp/RowOriented/ParquetFile.cs
- vcpkg_windows.bat
Updated to 1.5.1.1-beta2
Fixed handling of empty strings and ByteArrayConverter[] that could lead to null reference exceptions.
Added support for Decimal in RowOriented API (tuples are not currently supported, due to the need for an attribute).
Fixed BufferOutputStream.Finish(). 
Added gitattributes.
> Address multiple pending issues

- cpp/ColumnChunkMetaData.cpp
- csharp/ColumnReader.cs
- csharp/ExceptionInfo.cs
- csharp/IO/BufferOutputStream.cs
- csharp/IO/BufferReader.cs
- csharp/IO/ResizableBuffer.cs
- csharp/KeyValueMetadata.cs
- csharp/ParquetFileReader.cs
- csharp/ParquetFileWriter.cs
- csharp/ParquetHandle.cs
- csharp/ParquetSharp.csproj
- csharp/Schema/ColumnPath.cs
- csharp/Schema/GroupNode.cs
- csharp/SchemaDescriptor.cs
- csharp/WriterProperties.cs
- csharp/WriterPropertiesBuilder.cs
Bumped version to 1.5.1.1-beta4
Removed implicit conversion from ParquetHandle to IntPtr.
Added GC.KeepAlive to all ExceptionInfo.Return taking a ParquetHandle as argument.
Audited the code for more GC.KeepAlive when directly using IntPtr handles.
> Refactored and audited code for GC.KeepAlive

- csharp/ParquetSharp.csproj
- vcpkg_linux.sh
- vcpkg_windows.bat
Point back at vcpkg master, now that Arrow 0.14.1 port has been merged.
Bumped version to 2.0.1-beta1
> 2.0.1-beta1 with Arrow 0.14.1

- cpp/CMakeLists.txt
- cpp/ManagedOutputStream.cpp
- cpp/ManagedRandomAccessFile.cpp
- csharp.test/TestParquetFileReader.cs
- csharp.test/TestParquetPerformance.cs
- csharp/IO/BufferReader.cs
- csharp/IO/ManagedOutputStream.cs
- csharp/IO/ManagedRandomAccessFile.cs
- csharp/IO/OutputStream.cs
- csharp/IO/RandomAccessFile.cs
Adds ManagedRandomAccessFile and ManagedOutputStream, implementations of
the RandomAccessFile and OutputStream C++ interfaces that call back into
C# to read/write to a .Net IO.Stream.
This seems to be on par with performance from letting the C++ side
manage the file itself, that is pinvoke overhead appears minimal
relative to IO costs. The TestFloatTimeSeries benchmark has been updated
to write out by passing a filepath to C++, and by using
ManagedOutputStream.
Example output of TestFloatTimeSeries (with a slightly larger data size
than default):
Generating data...
Generated 31,200,000 rows in 0.78 sec
Saving to CSV
Saved to CSV (1,262,808,034 bytes) in 43.87 sec
Saving to CSV.GZ
Saved to CSV (317,658,548 bytes) in 92.55 sec
Saving to Parquet
Saved to Parquet (168,610,125 bytes) in 1.06 …
> ManagedRandomAccessFile/OutputStream to read/write to .Net IO.Streams

- cpp/ManagedOutputStream.cpp
- cpp/ManagedRandomAccessFile.cpp
- csharp.test/TestManagedRandomAccessFile.cs
- csharp/IO/ManagedOutputStream.cs
- csharp/IO/ManagedRandomAccessFile.cs
Add "leaveOpen" parameter to opt out of this (same parameter name as
StreamWriter/Reader).
> Close streams when Managed* classes are deleted

- cpp/CMakeLists.txt
- cpp/ManagedOutputStream.cpp
- cpp/ManagedRandomAccessFile.cpp
- cpp/WriterProperties.cpp
- cpp/WriterPropertiesBuilder.cpp
- csharp.test/ParquetSharp.Test.csproj
- csharp.test/TestDecimal128.cs
- csharp.test/TestManagedRandomAccessFile.cs
- csharp.test/TestPhysicalTypeRoundtrip.cs
- csharp.test/TestWriterProperties.cs
- csharp/IO/ManagedOutputStream.cs
- csharp/IO/ManagedRandomAccessFile.cs
- csharp/ParquetFileWriter.cs
- csharp/ParquetSharp.csproj
- csharp/RowOriented/ParquetFile.cs
- csharp/WriterProperties.cs
- csharp/WriterPropertiesBuilder.cs
- vcpkg_linux.sh
- vcpkg_windows.bat
- Version 2.0.2 Beta 2
- Upgraded to Arrow 0.15.1.
- Exposed CompressionLevel (new feature from Arrow).
- Use Lz4 by default instead of Snappy (empirically shown to be faster and compress better).
- Merged PR #76 (close streams when managed stream wrapper classes are closed).
> Upgrade to Arrow 0.15.1

- csharp.test/TestRowOrientedParquetFile.cs
- csharp/ParquetSharp.csproj
- csharp/RowOriented/ParquetFile.cs
- csharp/RowOriented/ParquetRowWriter.cs
KeyValueMetaData was also being ignored.
> Fixed compression argument being ignored by ParquetRowWriter.

- csharp.test/TestParquetPerformance.cs
- csharp/LogicalColumnReader.cs
- csharp/LogicalRead.cs
- Use DateTime ctor instead of FromBinary, as the later has more checks and overhead (fixes Issue #86).
- Do not use the conversion buffer if data can be read straight into the user destination buffer.
- Added more performance explicit unit tests.
> Improve logical column reader performance

- .github/workflows/linux.yml
- .github/workflows/windows.yml
Builds will still be triggered by pull requests.
For pushes, they will only be triggered if it's a push to the master branch.
> Avoid duplicate builds on pull requests

- csharp.test/TestRowOrientedParquetFile.cs
- csharp/ParquetSharp.csproj
- csharp/RowOriented/ParquetRowWriter.cs
Bumped release version to 2.1.0-beta2.
> Fixed row-oriented ParquetRowWriter not correctly writing empty row group (Issue #110).

- cpp/ManagedRandomAccessFile.cpp
- cpp/Node.cpp
- cpp/ReaderProperties.cpp
- cpp/ResizableBuffer.cpp
- csharp.test/TestColumn.cs
- csharp.test/TestWriterProperties.cs
- csharp/Encoding.cs
- csharp/ParquetSharp.csproj
- csharp/Schema/Node.cs
- vcpkg_linux.sh
- vcpkg_windows.bat
Fix API breakage and deprecated API calls.
Add support for new ByteStreamSplit encoding (Issue #112).
Should fix data corruption in Issue #116 (will merge the existing unit tests as part of another PR).
> Update to Arrow-0.17

- .github/workflows/ci.yml
Fix vcpkg caching on Windows, and use the vcpkg commit ID in the cache key, so that a branch name (i.e. `master`) can be used safely.
> Improve vcpkg cache

- vcpkg_linux.sh
- vcpkg_windows.bat
#129 introduced a typo in the Windows CI vcpkg build, which would make it fail once changing the version of vcpkg. This PR fixes it.
This PR also re-enables debug build of vcpkg in the Linux CI, as trying to build release-only currently fails on Linux.
> Fix broken vcpkg build

- csharp/ParquetSharp.csproj
This ensures ParquetSharpNative.dll is copied to all transitive consumers of this package.
> Add ParquetSharp.targets to the buildTransitive folder too

- vcpkg_windows.bat
Revised version of https://github.com/G-Research/ParquetSharp/pull/138 after comments
I think without the quotes it's not valid bat file syntax
`if %NOT_EXISTING_VAR%==true echo Hello`
works for me on the commandline but not in a batch file
http://steve-jansen.github.io/guides/windows-batch-scripting/part-5-if-then-conditionals.html
>  Fix vcpkg_windows.bat for case when GITHUB_ACTIONS is unset (Take 2)

- vcpkg_unix.sh
- vcpkg_windows.bat
This PR adds the ability to directly target a commit SHA in `vcpkg_version.txt`.
It can be useful when support for a new version of Arrow gets added to vcpkg, and we neither want to wait for a release of vcpkg, nor do we want to use `master`, as it could change at any time.
> Add support for commit SHA as ref in vcpkg_version.txt

- CMakeLists.txt
- cpp/CMakeLists.txt
- cpp/Enums.cpp
- csharp/ApplicationVersion.cs
- csharp/ByteArray.cs
- csharp/ColumnOrder.cs
- csharp/Compression.cs
- csharp/Date.cs
- csharp/DateTimeNanos.cs
- csharp/Encoding.cs
- csharp/Int96.cs
- csharp/PhysicalType.cs
- csharp/SortOrder.cs
- csharp/TimeSpanNanos.cs
Be more defensive about enum ABI compatibility breaks. See discussion at the bottom of https://github.com/apache/arrow/pull/7789
> Fix yet another ABI compression enum break from Arrow

- .github/workflows/ci.yml
A newer version of the microsoft/setup-msbuild action has been released that is not vulnerable to [CVE-2020-15228](https://github.com/actions/toolkit/security/advisories/GHSA-mfwh-5m23-j46w): https://github.com/microsoft/setup-msbuild/issues/26
This PR changes the version pinning to v1 instead of v1.0.0, so that the latest v1 will be used.
Fixes #154.
> Fix add-path warning in CI

- .github/workflows/ci.yml
Trying to resolve the vcpkg version of a commit SHA was giving an empty string, which was then causing the caching key to be wrong:
|      | Example |
| ---- | --- |
| Bad  | ![image](https://user-images.githubusercontent.com/3692455/95481412-448c0d80-098d-11eb-8c11-ed633601faa5.png) |
| Good | ![image](https://user-images.githubusercontent.com/3692455/95481570-6dac9e00-098d-11eb-9d76-103be935817a.png) |
This PR fixes that by first checking whether we already have a commit SHA in `vcpkg_version.txt`, and only resolving if it's a tag/branch name instead.
> Fix vcpkg cache in CI workflow

- csharp/RowOriented/ParquetFile.cs
- vcpkg_version.txt
I found an issue that when writing parquet files using a writer like:
```c#
var writer =
ParquetFie.CreateRowWriter<(long, int, double, int, long, short)>(
"path/to/my.parquet",
new [] {"C1", "C2", "C3", "C4", "C5", "C6"}
);
```
the resulting parquet file would have column C1 typed as `int` and C2 as `long` - i.e. the first two column types were swapped.
Upon debugging it transpired that this was when `Type.GetFields()` was being used to build the write delegate. `Type.GetFields()` was not returning fields in declaration order so the mapping of column name to type failed. The .NET docs for this method (and `Type.GetProperties()`) explicitly state that order is not guaranteed. So, I have changed the code to sort by `MemberInfo.MetadataToken` as advised in [this SO …
> Sort fields and properties by MetadataToken.

- csharp.test/TestRowOrientedParquetFile.cs
- csharp/RowOriented/ParquetFile.cs
Writing a decimal column was fine unless you provide custom column names. When custom column names were provided, writing failed when copying the `Column` object to set the name because the copy failed to provide the `LogicalTypeOverride` and the `Length`. This fixes that and adds test coverage.
> Writing decimals fails when column names provided

- .github/workflows/ci.yml
This PR fixes recent CI woes since GitHub started deploying .NET 5.0.200 as the default SDK on their GitHub Actions runners (see failure examples [here](https://github.com/G-Research/ParquetSharp/pull/168/checks?check_run_id=2098347678) and [here](https://github.com/G-Research/ParquetSharp/pull/167/checks?check_run_id=2098093685)).
The behaviour of the `test-nuget` job is changed as follows: NuGet sources are specified in the right order in the top-level config and the implicit restore done during the package add will then use it instead of a unique source specified on the command line.
Before .NET 5.0.200, the implicit restore was also considering the nuget.org source, so this problem never occured.
> Fix CI with .NET >= 5.0.200

- .github/workflows/ci.yml
This PR pins the version of the .NET Core SDK used in the CI to avoid building/testing with a random version decided by GitHub. It does so by generating a `global.json` file during the workflow run. This prevents `dotnet` from using the latest available SDK installed on the GitHub Actions runner.
This PR also upgrades the CI workflow to use the latest version of .NET Core 3.1 (3.1.407) and disables displaying the "welcome screen" (aka the logo).
> Pin .NET Core SDK version in CI

- .github/workflows/ci.yml
According to the NuGet documentation and my own empirical testing, NuGet will always check our local source first, so the reordering attempted in #170 is a no-op.
The [documentation](https://docs.microsoft.com/en-us/nuget/concepts/package-installation-process) states:
> When acquiring the package, the order of sources in the NuGet configuration may apply:
> * NuGet checks sources local folder and network shares before checking HTTP sources.
> Remove NuGet source reordering as it is actually a no-op

- README.md
- csharp.benchmark/ParquetSharp.Benchmark.csproj
- csharp.test/ParquetSharp.Test.csproj
Parquet.NET issue has been fixed, update benchmark numbers in README.
Update build dependencies in README.
> Update tests and benchmarks to Parquet.NET 3.8.6.

- .github/workflows/ci.yml
- csharp.test/ParquetSharp.Test.csproj
- csharp/ParquetSharp.csproj
This PR modifies the test project to allow running on the .NET 5.0 runtime ~~when `-p:Channel=experimental` is specified~~. This requires building with the .NET 5.0 SDK, which might have an impact on the code we generate, though that should not be the case. It also requires contributors to have it installed to be able to build the tests.
This PR also modifies the CI workflow to run the tests on .NET 5.0 in parallel to .NET Core 3.1 and .NET Framework 4.6.1.
> Test dotnet 5

- csharp/ParquetSharp.csproj
Arrow 4.0.0 has been released, so time to start a new beta branch.
Clarification: 2.4.0 uses Arrow 3.0.0. Let's release that as non-beta, as it's been stable for a while. Then we start 2.5.0-beta ultimately targeting Arrow 4.0.0 when available on vcpkg.
> Promoting 2.4.0-beta2 to release version.

- csharp/Date.cs
- csharp/DateTimeNanos.cs
Was trying to sort some rows generically, it failed because Date is not IComparable.
> Make Date : IComparable<Date>, DateTimeNanos : IComparable<DateTimeNanos>

- csharp/Date.cs
- csharp/DateTimeNanos.cs
If `Date` implements it, `DateTimeNanos` should too.
> Be consistent in the Equals/CompareTo interfaces for Date and DateTimeNanos

- csharp.test/TestColumnPath.cs
- csharp.test/TestNode.cs
- csharp.test/TestParquetFileWriter.cs
- csharp/AadPrefixVerifier.cs
- csharp/ApplicationVersion.cs
- csharp/ColumnCryptoMetaData.cs
- csharp/ColumnDecryptionPropertiesBuilder.cs
- csharp/ColumnDescriptor.cs
- csharp/ColumnEncryptionPropertiesBuilder.cs
- csharp/DecryptionKeyRetriever.cs
- csharp/ExceptionInfo.cs
- csharp/FileDecryptionProperties.cs
- csharp/FileDecryptionPropertiesBuilder.cs
- csharp/FileEncryptionProperties.cs
- csharp/FileEncryptionPropertiesBuilder.cs
- csharp/FileMetaData.cs
- csharp/KeyValueMetadata.cs
- csharp/ParquetFileReader.cs
- csharp/ParquetFileWriter.cs
- csharp/ParquetSharp.csproj
- csharp/Schema/ColumnPath.cs
- csharp/Schema/GroupNode.cs
- csharp/Schema/PrimitiveNode.cs
- csharp/SchemaDescriptor.cs
- csharp/StringUtil.cs
- csharp/WriterPropertiesBuilder.cs
Fixes Issue #205.
Doing this PR requires `[MarshalAs(UnmanagedType.LPUTF8Str)]` which is only supported in net47 or higher. This means I've taken the decision to retire support for .NET Framework 4.6.1 and .NET Core 2.0 or lower. Otherwise, the code would be significantly more complicated and require explicit conversion of all strings to UTF8 before calling into the native methods. Even so, I had to backport `PtrToStringUTF8` from .NET Standard 2.1 (can't believe marshalling UTF8 wasn't properly supported until .NET Core 3.0).
The rest should be less controversial.
One area I'm not sure is `key_id` vs `key_metadata`. I think one of them is meant to be a byte array while the other should be a UTF8 string. But the documentation is lacking. This PR does not address this ambiguity (left out …
> Add proper UTF8 Support

- .github/workflows/ci.yml
This should fix "The repository primary signature validity period has expired" errors on macOS.
See https://github.com/dotnet/core/issues/6595
> Bump version of dotnet 5 SDK used in CI

- .github/workflows/ci.yml
This PR enables the automatic creation of a draft GitHub release with the NuGet Package when a tag is created, as well as uploading the package to nuget.org.
> Automatic NuGet and release publication

- csharp.test/TestLogicalTypeRoundtrip.cs
* Re-enables checking of null counts, which were previously broken for array valued columns
* Re-enables checking min/max for decimals, which has been fixed since Arrow 4.0
> Statistics test updates for Arrow 6.0.0

- CMakeLists.txt
- README.md
- cpp/Enums.cpp
- csharp.test/TestLogicalTypeRoundtrip.cs
- csharp.test/TestPhysicalTypeRoundtrip.cs
- csharp.test/TestWriterProperties.cs
- csharp/Encoding.cs
- csharp/ParquetSharp.csproj
- csharp/ParquetVersion.cs
- vcpkg_version.txt
Closes #222.
Closes #68.
Closes #229.
Supersedes #230.
> Update to Arrow 6.0.1

- csharp.test/TestLogicalTypeRoundtrip.cs
- csharp/LogicalColumnReader.cs
Would close https://github.com/G-Research/ParquetSharp/issues/242
> Fix GetEnumerator

- .github/workflows/ci.yml
- README.md
- build_windows.bat
GitHub has started rolling out Windows Server 2022 to GitHub actions jobs running on `windows-latest`: https://github.blog/changelog/2022-01-11-github-actions-jobs-running-on-windows-latest-are-now-running-on-windows-server-2022/
This image includes Visual Studio 2022 instead of 2019, so I've updated the build script to expect VS 2022, and explicitly set the Windows image to windows-2022 in the CI configuration so we're pinned to one version rather than randomly getting either 2019 or 2022 during the roll out.
Alternatively we could just stick with 2019, but I think it's best to keep up to date.
> Support Windows Server 2022 CI builds

- csharp/ParquetSharp.csproj
Because of changes in vcpkg/msys2, the build was not reproducible anymore. @adamreeve fixed it in #265.
This means that even though none of our code changed between 6.0.1-beta1 and now, some of our indirect dependencies got upgraded. Here is the list:
- boost: 1.77.0 -> 1.78.0
- openssl: 1.1.1l -> 1.1.1n
- zstd: 1.5.0 -> 1.5.2
> Promote 6.0.1-beta1 to stable release

- .github/workflows/ci.yml
The `vcpkg` binary caching in our CI currently gets [broken](https://github.com/G-Research/ParquetSharp/runs/6121033684?check_suite_focus=true) when a cache entry gets [generated](https://github.com/G-Research/ParquetSharp/runs/6121033684?check_suite_focus=true) with a given version of `cmake` and then gets [used](https://github.com/G-Research/ParquetSharp/runs/6121033684?check_suite_focus=true#step:4:18) with a different version, e.g. when the runner virtual environment gets upgraded (`macOS-11` [20220410.1](https://github.com/actions/virtual-environments/blob/macOS-11/20220410.1/images/macos/macos-11-Readme.md#tools) vs [20220419.3](https://github.com/actions/virtual-environments/blob/macOS-11/20220419.3/images/macos/macos-11-Readme.md#tools)).
The broken cache entry then keeps on …
> Fix vcpkg binary caching in CI

- .github/workflows/ci.yml
- build_unix.sh
This PR aims at fixing #273 by building the linux-x64 native library within a CentOS 7 container with GCC 7. This allows linking with older versions of the system libraries, widening the Linux distributions supported by our NuGet package.
Please note that the linux-arm64 native library is still built on Ubuntu 18.04, as there is no recent cross-compiler available on CentOS 7. We will probably need to first get self-hosted linux-arm64 runners before we can support this. All of this being said, I don't expect many people to use old Linux distributions on arm64.
> Build linux-x64 in a CentOS 7 container for backwards compatibility

- csharp.test/TestDecimal128.cs
I have changed the TestScaleOverflow test to use an fixed culture (en-US), as otherwise the test may fail depending on the users local culture.
An example is Danish where "," is the decimal separator instead of "."
> Use fixed culture when testing OverflowException

- cpp/KeyValueMetadata.cpp
- cpp/ParquetFileWriter.cpp
- csharp.test/TestKeyValueMetadata.cs
- csharp/KeyValueMetadata.cs
- csharp/ParquetFileWriter.cs
This PR changes ParquetFileWriter so that it doesn't read the KeyValueMetadata dictionary until the file is closed, to allow metadata entries to be added or updated at any time before the file is closed.
Internally, the Arrow C++ ParquetFileWriter takes a `std::shared_ptr<const KeyValueMetadata>` and then doesn't read the entries from the metadata until the file is closed and the footer is written, so this behaviour closely maps to the C++ API.
This changes behaviour and has the potential to be a breaking change if anyone is relying on being able to modify the metadata dictionary after passing it to the ParquetFileWriter constructor without this affecting the written metadata. That seems fairly unlikely though.
> Allow updating key-value metadata after ParquetFileWriter creation

- .github/workflows/ci.yml
- csharp.benchmark/ParquetSharp.Benchmark.csproj
- csharp.test/ParquetSharp.Test.csproj
- csharp.test/Program.cs
- global.json
This PR adds support for .NET 6, both in project files and in the CI.
Summary of the changes:
- require .NET 6 SDK to build via `global.json`
- add `net6.0` to test target frameworks, and only build for it by default
- switch target framework to `net6.0` for benchmarks
- use `HandleProcessCorruptedStateExceptions` on .NET Framework only (it never worked on .NET Core and is unavailable on .NET 6)
- always use the latest 6.0.x SDK instead of a pinned version in CI
- daily CI runs of the CI to get notified of potential build failures when a new version of the SDK is released
- CI runs on both macOS 10.15 and 11.0
> Add support for .NET 6

- csharp.test/TestByteArrayReaderCache.cs
- csharp.test/TestColumn.cs
- csharp.test/TestColumnPath.cs
- csharp.test/TestDecimal128.cs
- csharp.test/TestEncryption.cs
- csharp.test/TestLogicalTypeFactory.cs
- csharp.test/TestLogicalTypeRoundtrip.cs
- csharp.test/TestMemoryLeaks.cs
- csharp.test/TestNestedReads.cs
- csharp.test/TestNode.cs
- csharp.test/TestParquetFileReader.cs
- csharp.test/TestParquetFileWriter.cs
- csharp.test/TestPhysicalTypeRoundtrip.cs
- csharp.test/TestRowOrientedParquetFile.cs
- csharp/Column.cs
- csharp/ColumnDescriptor.cs
- csharp/LogicalColumnReader.cs
- csharp/LogicalColumnStream.cs
- csharp/LogicalColumnWriter.cs
- csharp/LogicalRead.cs
- csharp/LogicalTypeFactory.cs
- csharp/LogicalWrite.cs
- csharp/ParquetFileReader.cs
- csharp/Schema/GroupNode.cs
- csharp/Schema/PrimitiveNode.cs
In this PR I've tried to dispose of most internal uses of LogicalType and Node to reduce the need to run finalizers.
There is still one main place where we create logical types and nodes that aren't disposed that I'm aware of. In LogicalColumnStream, the LogicalType and SchemaNodesPath properties are initialized in the constructor rather than being getters that create new instances, so these should probably be disposed when disposing the LogicalColumnStream instance. But there's a small chance that could be a breaking change if somebody is expecting to be able to continue using those after the LogicalColumnStream is disposed, so I've currently left that as-is.
There's also `RowOriented.ParquetFile.GetColumn` which creates logical types that aren't disposed, and I couldn't see a …
> Dispose of most uses of LogicalType and Node

- csharp.test/TestLogicalTypeRoundtrip.cs
- csharp/LogicalRead.cs
- csharp/LogicalTypeFactory.cs
- csharp/LogicalWrite.cs
This fixes #292 by updating the `LogicalTypeFactory` to handle string columns where repetition is set to required, and fixing the definition level handling when reading and writing required string data.
> Handle reading and writing string values without definition levels

- .github/workflows/ci.yml
Build in MacOS 11 and test in MacOS 11 and 12, as the MacOS 10.15 runner is being deprecated
> Update MacOS versions used in CI

- csharp.benchmark/FloatArrayTimeSeriesRead.cs
- csharp.benchmark/ParquetSharp.Benchmark.csproj
- csharp.benchmark/Program.cs
- csharp/BufferedReader.cs
- csharp/LogicalColumnReader.cs
This PR changes how array values are read to avoid growing lists dynamically, and instead create arrays directly from spans of the buffered logical values.
This is based on the work done by @philjdf in https://github.com/philjdf/ParquetSharp/pull/4 and https://github.com/philjdf/ParquetSharp/pull/5. The new benchmark has mostly been copied as-is, but the array reading changes have been adapted to work with the latest master code.
On my machine (AMD Ryzen 9 5900 X with 64 GB RAM running Fedora Linux 36 with dotnet SDK 6.0.107), I get the following benchmark results:
| Test case | Time taken (s) | Time taken with server GC (s) |
| --- | --- | --- |
| Parquet.Net | 10.8 | 10.1 | 
| ParquetSharp 7.0 | 20.4 | 20.9 |
| ParquetSharp 8.0 beta | 12.5 | 10.9 |
| ParquetSharp with this PR | 4.5 | …
> Read whole leaf-level arrays at once when possible, rather than growing lists

- csharp.test/TestCaseGenericAttribute.cs
- csharp.test/TestLogicalTypeRoundtrip.cs
- csharp/LogicalTypeFactory.cs
_This PR is on behalf of @msumner91._
The goal is to fix the following exception:
```
System.ArgumentOutOfRangeException: unsupported logical type Null with physical type Int32
Parameter name: logicalType
at ParquetSharp.LogicalTypeFactory.GetSystemTypes(ColumnDescriptor descriptor)
at ParquetSharp.LogicalTypeFactory.GetSystemTypes(ColumnDescriptor descriptor, Type columnLogicalTypeOverride)
at ParquetSharp.ColumnDescriptor.GetSystemTypes(LogicalTypeFactory typeFactory, Type columnLogicalTypeOverride)
```
> Allow NullLogicalType given a PhysicalType

- csharp.test/TestManagedRandomAccessFile.cs
- csharp/IO/ManagedOutputStream.cs
- csharp/IO/ManagedRandomAccessFile.cs
- csharp/ParquetFileReader.cs
- csharp/ParquetFileWriter.cs
This fixes crashes when users don't keep a reference to a `ManagedOutputStream` or `ManagedRandomAccessFile` while they are in use. They should still be used with a using statement so that the handle is freed immediately when no longer needed though.
A reference to the managed objects is captured in the handle free functions so that they are kept alive until after the handle is freed. `ParquetFileReader` and `ParquetFileWriter` now also keep references to the `RandomAccessFile` and `OutputStream` instances if used to ensure they aren't GC'd until after they are no longer needed.
Fixes #312
> Avoid use of ManagedOutputStream and RandomAccessFile after GC

- csharp.test/TestDecimal.cs
- csharp/LogicalRead.cs
- csharp/LogicalTypeFactory.cs
- csharp/LogicalWrite.cs
Fixes #314, based on code by @fan130 in https://github.com/fan130/ParquetSharp/commit/7b7a5d4968a6ac35cde96d4b2343cfd5a5b26f36 but also supporting reading int32 data.
> Support reading decimal data with int32 or int64 physical type

- csharp.test/TestParquetFileWriter.cs
- csharp/LongPath.cs
- csharp/ParquetFileReader.cs
- csharp/ParquetFileWriter.cs
- docs/Reading.md
Although Arrow was updated to use long-path aware win32 APIs (#114), there are additional configuration requirements needed to handle long paths, so I've added documentation on this.
In addition, paths need to be provided in extended-length format, even in dotnet core, so I've added code to do this conversion automatically for absolute paths.
> Convert paths to extend length format on Windows and add documentation on long path support

- csharp.test/TestManagedRandomAccessFile.cs
- csharp/ParquetFileReader.cs
- csharp/ParquetFileWriter.cs
This PR adds some convenience constructors that allow reading or writing a .NET stream directly without having to create a `ManagedRandomAccessFile` or `ManagedOutputStream` explicitly.
> Allow creating a ParquetFileReader/Writer directly from a .NET stream

- csharp.test/TestLogicalTypeRoundtrip.cs
- csharp.test/TestMaps.cs
- csharp/BufferedReader.cs
Fixed a bug and added unit tests to cover nested-nested types writing/reading when nested is list and nested-nested is either optional parquet list or parquet map with a required leaf field.
> Support of optional nested-nested types reading

- README.md
- cpp/CMakeLists.txt
- csharp.test/ParquetSharp.Test.csproj
- csharp.test/TestDecimal128.cs
- csharp.test/TestPhysicalTypeRoundtrip.cs
- csharp.test/TestWriterProperties.cs
- csharp/ParquetSharp.csproj
- docs/Reading.md
- vcpkg-configuration.json
- vcpkg.json
This upgrades the version of Arrow used to 10.0.1 and bumps the ParquetSharp version to 10.0.0-beta1.
The main user-visible change with this is that the default version of the Parquet format to write is now 2.4. The Arrow Jira issue that explains the motivation for this is https://issues.apache.org/jira/browse/ARROW-12203.
I believe the points about supported time and integer types are not relevant to us as these only affect type mappings when converting from Arrow data, and we already used these new types when writing 1.0 versioned files with the corresponding .NET types. One change that could cause issues is that dictionary encoded data now uses the `RleDictionary` encoding by default rather than `PlainDictionary`, which could cause compatibility issues with old versions of some …
> Upgrade to Arrow 10.0.1

- csharp/ParquetSharp.csproj
- docs/Reading.md
Use version 10.0.1 rather than 10.0.0 to match the Arrow version. I'd originally used 10.0.0 in #321, thinking only the major version needed to match Arrow and we would leave patch versions for any ParquetSharp changes. But Jonathan pointed out we previously released 6.0.1 to match the Arrow 6.0.1 version, and could always release a 10.0.1.1 version if we need a ParquetSharp specific bug fix release.
> Change version to 10.0.1 to match Arrow

- .github/workflows/ci.yml
- CMakeLists.txt
- csharp/RowOriented/ParquetFile.cs
- docs/RowOriented.md
- fsharp.test/ParquetSharp.Test.FSharp.fsproj
- fsharp.test/TestRowOrientedApi.fs
Fixes #329 by allowing the `MapToColumn` attribute to be used on private properties, and throwing an exception if a type has no public fields or properties, and no private fields or properties annotated with `MapToColumn`.
> Fix using internal F# types with the row oriented API

- .gitignore
- README.md
- csharp.benchmark/DecimalRead.cs
- csharp.benchmark/DecimalWrite.cs
- csharp.benchmark/FloatArrayTimeSeriesRead.cs
- csharp.benchmark/FloatTimeSeriesRead.cs
- csharp.benchmark/FloatTimeSeriesWrite.cs
- csharp.benchmark/ParquetSharp.Benchmark.csproj
This updates the benchmark code to work with the latest version of Parquet.Net and updates the results in the README.
I also took a look at reproducing the benchmark results that were published by the author of Parquet.Net in https://www.aloneguid.uk/posts/2023/01/parquet-dotnet-vs-parquet-sharp/ and https://github.com/aloneguid/parquet-dotnet/releases/tag/4.2.0
I get similar results to them when running on my machine, with much slower times to write 1,000,000 random integers or floats with ParquetSharp compared to Parquet.Net. It looks like this is due to our (or really Apache Arrow's) default behaviour of using dictionary encoding for all columns. If I disable dictionary encoding for these columns it makes us about 10x faster than we were, or 2x faster than Parquet.Net. Parquet.Net only …
> Update benchmark code and results

- README.md
- docs/Nested.md
Fixes #339 by explaining that we want to write one object per row in the Parquet file, and explains why we don't just use a `message` and `ids` column.
I also removed the outdated paragraph in the README under `Known Limitations` about not being able to fully interpret nested data.
> Update nested data documentation

- .github/workflows/ci.yml
as `ubuntu-18.04` runners are deprecated, we should remove them and use `ubuntu-20.04` for now
> remove deprecated ubuntu-18.04 runners

- csharp.test/TestRowOrientedParquetFile.cs
- csharp/RowOriented/ParquetRowWriter.cs
When an error is encountered flushing row-oriented data to Parquet, eg. an out-of-memory error, make sure we don't later retry writing when the `ParquetRowWriter` is disposed as this can lead to unhandled native exceptions for mismatching row counts if data has been partially written.
> Don't retry writing in Dispose after encountering an error in ParquetRowWriter

- csharp.test/TestDecimal128.cs
- csharp.test/TestLogicalTypeFactory.cs
- csharp/Column.cs
- csharp/LogicalWrite.cs
This allows use of custom converters that support different precision and type lengths.
Fixes #347
> Defer checking decimal precision and type length until creating converter

- README.md
- cpp/WriterProperties.cpp
- cpp/WriterPropertiesBuilder.cpp
- csharp.test/TestPhysicalTypeRoundtrip.cs
- csharp.test/TestWriterProperties.cs
- csharp/DefaultWriterProperties.cs
- csharp/ParquetSharp.csproj
- csharp/WriterProperties.cs
- csharp/WriterPropertiesBuilder.cs
- vcpkg-configuration.json
- vcpkg.json
Upgrades the version of the Arrow C++ library used to 12.0.1. Fixes #355 and fixes reading nullable byte-stream-split encoded data (#237) as this was fixed in Arrow.
This PR also exposes the new `write_page_index` option in the writer properties, which was added in Arrow 12.
~~The main change that might affect users is that the default row group size has been reduced from 64 Mi to 1 Mi (see https://github.com/apache/arrow/pull/34281).~~ Actually this is only used when writing Arrow tables or record batches, when using ParquetSharp users control batching into row groups, even with the row-oriented API, so this change should have no effect.
I've run the benchmarks and didn't find any significant performance differences.
> Upgrade to Arrow 12.0.1

- .github/workflows/ci.yml
- csharp.benchmark/ParquetSharp.Benchmark.csproj
- csharp.test/ParquetSharp.Test.csproj
- fsharp.test/ParquetSharp.Test.FSharp.fsproj
- global.json
#363 started the migration to `net7.0` but stopped short of running actual tests and building with the `net7.0` SDK — this PR aims at fixing that.
> Finalize net7.0 migration

- .github/workflows/ci.yml
The "All required checks done" CI job has been designed to be a required check, but GitHub considers it successful when it's skipped, and it gets skipped when some of the jobs it depends on fail.
This PR fixes that by always running the job and checking the results of all the jobs it depends on.
Example runs:
- [all jobs successful](https://github.com/jgiannuzzi/fasttrackml/actions/runs/5835414192)
- [some jobs failed](https://github.com/jgiannuzzi/fasttrackml/actions/runs/5835422840)
> Fix "All required checks done" CI job to never be skipped

- .github/workflows/check-required.yml
- .github/workflows/ci.yml
The "All required checks done" CI job has been designed to be a required check, but GitHub considers it successful when it's skipped, and it gets skipped when some of the jobs it depends on fail. A first attempt at fixing that was made in #366 but it was not enough.
This PR fixes that by checking in a separate workflow whether the job conclusion is `success` and creates a new check run "All required checks **succeeded**" when it's the case. When it's not the case, the check run is not created and PRs will thus not be mergeable.
Example runs:
- [successful run](https://github.com/jgiannuzzi/fasttrackml/actions/runs/5858130823) — the [check run](https://github.com/jgiannuzzi/fasttrackml/runs/15881484894) is created by this [workflow …
> Create "All required checks succeeded" check run when "All required checks done" CI job is actually successful

- README.md
- cpp/WriterProperties.cpp
- cpp/WriterPropertiesBuilder.cpp
- csharp.test/TestPhysicalTypeRoundtrip.cs
- csharp.test/TestWriterProperties.cs
- csharp/ParquetSharp.csproj
- csharp/WriterProperties.cs
- csharp/WriterPropertiesBuilder.cs
- vcpkg-configuration.json
- vcpkg.json
This upgrades the version of the Arrow C++ library to 13.0.0.
The notable changes in this version are:
* Writing the page index can now be controlled per column
* The Parquet version written now defaults to 2.6. This version includes the nanosecond timestamp precision but we were already using this in ParquetSharp so this change doesn't seem to affect us besides the metadata being different
* Changes to how the column encodings are computed affected the order these are returned in, but the order shouldn't have been relied on
Comparing benchmark results between the current master and this branch, the timings are mostly the same, with some of the "chunked" writing tests slowing down a little (5 to 10%) indicating there might be a bit more per-row-group overhead. There is quite a large …
> Upgrade to Arrow 13.0.0

- csharp.test/ParquetSharp.Test.csproj
- csharp.test/TestColumn.cs
- csharp.test/TestDecimal128.cs
- csharp.test/TestLogicalTypeRoundtrip.cs
- csharp.test/TestPhysicalTypeRoundtrip.cs
- fsharp.test/ParquetSharp.Test.FSharp.fsproj
Running the tests under Visual Studio Code with the C# Dev Kit extension would include tests marked explicit, leading to surprises like the `StressTestProcessMemory` test running for a long time. This is fixed by upgrading the version of the `NUnit3TestAdapter` package, but this also seems to have changed behaviour so that now any console logging from tests is output by default when running `dotnet test`. The tests were doing a lot of logging, over 80k lines, so I've also removed some logging I thought was unnecessary and changed some logs to only be shown in the case of an error where they add some useful context.
> Upgrade the NUnit test adapter

- README.md
This documents the workarounds I had to use to get the dev container working on Fedora 38 with SELinux and podman. I've put these in a collapsible section as they won't be relevant for most users, but it seems worth having them documented here in case anybody else has similar issues.
> Document workarounds for using the dev container with podman and SELinux

- README.md
I'm Juan, an MLH Fellow, and my goal is to improve G-Research projects by making them more accessible to new users and contributors by reducing friction while browsing and learning how to use each project.
I hope these changes to the README make sense:
- Added details about Parquet to the README
- New users that stumble upon the repo may not be completely aware of **what Parquet is** and **why we should use it**.
- Added supporting fact and source (source links improve SEO by increasing credibility)
- New section was added to make the extra info unobtrusive and improve SEO by hitting the "why use parquet" query keywords
- Changed wording for quickstart sections and made them more visible
- This is one of the most important parts of the README, so visual cues help users find what they want …
> README Enhancements

- .github/workflows/ci.yml
GitHub has _finally_ [announced](https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/) support for Apple Silicon in GitHub Actions. This PR enables them according to the [documentation](https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/about-larger-runners#about-macos-larger-runners) by adding a `macos-13-xlarge` label.
Closes #233.
> Run tests on Apple Silicon

- docs/Arrow.md
- docs/Nested.md
- docs/Reading.md
- docs/TypeFactories.md
- docs/Writing.md
Hi, I'd like to make a few minor changes to the documentation files to make them more readable.
- Added headers to separate content into bite-sized pieces
- Makes the documentation easier to browse
- Improves SEO by adding context to each document
- Standardized whitespaces and punctuation
- Slightly improves readability (especially for anybody editing docs)
- Reordered `Writing.md` schema creation section to have high-level API shown first, and added an internal link to an example of the graph API
- This improves developer experience by emphasizing the easier way of doing things while also giving an example for the lower-level API
- Fixed various typos and improved wording
- Fixed minor typo in code snippet
- Fixed references to `LogicalColumnWriter` and `LogicalColumnReader` to aid SEO …
> Documentation Enhancements

- csharp.test/ParquetSharp.Test.csproj
Fix test not runnable from VS UI, even though they are found. Error:
```
The following test container was not found: 'ParquetSharp\csharp.test\bin\Debug\net7.0\ParquetSharp.Test.dll'. This can be resolved by one or more of the following steps:
1. The test container does not exist on disk and the corresponding project might need to be built successfully.
2. For .NET Core based test projects, please ensure that a nuget package reference to "Microsoft.NET.Test.SDK" exists and that it uses the latest stable version.
3. For .NET based test projects, the project might be marked as a non-test project through an msbuild property, "IsTestProject". Please consider clearing it or set "<IsTestProject>true</IsTestProject>" in a "<PropertyGroup>" in the test project.
```
> test: update Microsoft.NET.Test.Sdk

- csharp.test/ParquetSharp.Test.csproj
- csharp.test/TestRowOrientedParquetFile.cs
- csharp/RowOriented/ParquetFile.cs
- csharp/RowOriented/ParquetRowReader.cs
- csharp/RowOriented/ParquetRowWriter.cs
- docs/RowOriented.md
- Added support for custom conversion logic for Row-oriented API
- Allow passing the `LogicalReadConverterFactory` and `LogicalTypeFactory` when invoking `ParquetFile.CreateRowReader()`
- Allow passing the `LogicalWriteConverterFactory` and `LogicalTypeFactory` when invoking `ParquetFile.CreateRowWriter()`
- Made internal changes to `ParquetFile`, `ParquetRowReader` and `ParquetRowWriter` to allow setting the factories
- Added a unit test for new feature
**Note:** Currently, argument names must be explicitly mentioned when using the logical factories for writing:
`using var writer = ParquetFile.CreateRowWriter<TTupleWrite>(outputStream, columnNames: columnNames, logicalTypeFactory: logicalWriteTypeFactory, logicalWriteConverterFactory: logicalWriteConverterFactory);`
I wasn't sure how to …
> Add support for custom conversion logic with Row-oriented API

- README.md
- csharp.test/TestPhysicalTypeRoundtrip.cs
- csharp.test/TestWriterProperties.cs
- csharp/ParquetSharp.csproj
- vcpkg.json
This upgrades to Arrow version 14.0.2, which contains a bug fix for an error being raised with large dictionary encoded columns (https://github.com/apache/arrow/issues/38577)
> Upgrade Arrow C++ to 14.0.2

- .devcontainer/Dockerfile
After upgrading to Arrow 14.0.2 the devcontainer build failed due to not finding that Arrow version in vcpkg (https://github.com/G-Research/ParquetSharp/actions/runs/7458957587/job/20293957096), although the devcontainer build had passed in the PR.
It looks like this is because the docker build used a cached result of checking out the vcpkg repository from before Arrow 14.0.2 was added.
I've moved the copy of vcpkg.json to before the vcpkg repo checkout, so any changes to vcpkg.json should force a new checkout of vcpkg rather than use the previously cached result.
> Copy vcpkg.json before cloning vcpkg in devcontainer Dockerfile

- .github/workflows/ci.yml
- ParquetSharp.DotSettings
Based on existing rule sets in [ParquetSharp.DotSettings](https://github.com/ljubon/ParquetSharp/blob/oss-414-linting-lvl-4/ParquetSharp.DotSettings) and as part of [OSS-414](https://github.com/G-Research/oss-portfolio-maturity/issues/414) goal of this PR is to add new rules which are safe and not breaking current process, just enforcing existing syntax and style
_Optional_: I tried one more rule to add, but it's not part of this PR
Here are [changes ](https://github.com/ljubon/ParquetSharp/actions/runs/7506069064/job/20436665643#step:4:3173), total `67` file
Rule line is:
```xml
<s:Boolean x:Key="/Default/CodeStyle/CodeFormatting/CSharpFormat/SPACE_AFTER_TYPECAST_PARENTHESES/@EntryValue">False</s:Boolean>
```
> Lint: Update rules for formating code

- cpp/LogicalType.cpp
- csharp.test/TestLogicalTypeRoundtrip.cs
- csharp/AadPrefixVerifier.cs
- csharp/ByteArray.cs
- csharp/ByteArrayReaderCache.cs
- csharp/Column.cs
- csharp/Date.cs
- csharp/DateTimeNanos.cs
- csharp/DecryptionKeyRetriever.cs
- csharp/FixedLenByteArray.cs
- csharp/LogicalBatchReader/LogicalBatchReaderFactory.cs
- csharp/LogicalBatchWriter/LogicalBatchWriterFactory.cs
- csharp/LogicalRead.cs
- csharp/LogicalType.cs
- csharp/LogicalTypeFactory.cs
- csharp/LogicalWrite.cs
- csharp/ParquetSharp.csproj
- csharp/RowOriented/ParquetFile.cs
Fixes #413 
This adds support for the new `Float16` logical type added in Arrow 15. I've added a new .NET 6 target to the ParquetSharp project to allow using the new `Half` type, which required fixing a few errors related to nullable reference type checking when building with the newer target.
One thing to be aware of is that writing `Half` values can be a bit slower than floats because of the extra overhead of writing these as fixed-length byte arrays rather than having a dedicated physical type. We could possibly improve this in future if it turns out to be a problem. I did some quick benchmarking of reading and writing 1 million random floats, doubles and half values, with dictionary encoding disabled:
|     Method |     Mean |     Error |    StdDev | Ratio | RatioSD |
|----------- …
> Add support for reading and writing the .NET Half type

- cpp/ReaderProperties.cpp
- cpp/WriterProperties.cpp
- cpp/WriterPropertiesBuilder.cpp
- csharp.test/TestReaderProperties.cs
- csharp.test/TestWriterProperties.cs
- csharp/DefaultWriterProperties.cs
- csharp/ReaderProperties.cs
- csharp/WriterProperties.cs
- csharp/WriterPropertiesBuilder.cs
These options were added back in Arrow 12, but I noticed Arrow 15 added them to the Python API, and it seemed like an easy thing to add and could be useful for some users.
> Expose page checksum verification reader and writer properties

- README.md
- csharp.test/TestLogicalTypeRoundtrip.cs
- csharp/LogicalRead.cs
- csharp/LogicalTypeFactory.cs
- csharp/LogicalWrite.cs
- docs/TypeFactories.md
Fixes #423 
This adds support for converting to and from the .NET `TimeOnly` and `DateOnly` types when using the .NET 6 target. For the `TimeOnly` type, I've added support for millisecond and microsecond precision, matching the existing `TimeSpan` conversion behaviour.
In addition, I've added two options to allow customizing the built-in `LogicalTypeFactory` class so that these types can be used by default instead of the `ParquetSharp.Date` and `TimeSpan` types. I've made these settable properties so that they can be modified on the default `LogicalTypeFactory` instance to allow changing the process-wide behaviour. I'd usually tend towards using immutable objects, but in this case it seems worthwhile to allow configuring this without too much boilerplate. I'm open to other suggestions on …
> Support the TimeOnly and DateOnly types added in .NET 6

- csharp/ParquetSharp.csproj
This bumps the version to 15.0.0-beta2 so we can make a new beta release with the new encryption API
> Bump version to 15.0.0-beta2

- cpp/arrow/FileWriter.cpp
- csharp.test/Arrow/TestFileWriter.cs
- csharp/Arrow/FileWriter.cs
- csharp/Encryption/CryptoFactory.cs
- csharp/ParquetSharp.csproj
- docs/Arrow.md
This adds support for writing Arrow format data in buffered mode, so that multiple record batches can be written to the same Parquet row group.
This diverges a bit from the C++ API, which has `WriteTable` which starts a new row group, and `WriteRecordBatch` which is buffered. As we already have a `WriteRecordBatch` method that uses `WriteTable` internally, I've added a new `WriteBufferedRecordBatch` method.
> Support buffered writing with the Arrow API

- README.md
- csharp.test/TestPhysicalTypeRoundtrip.cs
- csharp.test/TestWriterProperties.cs
- csharp/ParquetSharp.csproj
- vcpkg.json
This PR upgrades Arrow from 15.0.0 to 15.0.2.
There don't appear to be any major changes or critical fixes, the two relevant changes I can see are:
* https://github.com/apache/arrow/issues/39527 - Page sizes are not always validated before truncating to int32
* https://github.com/apache/arrow/issues/40068 - Possible data race when reading metadata of a parquet file
> Upgrade Arrow C++ version to 15.0.2

- cpp/CMakeLists.txt
- cpp/arrow/FileReader.cpp
- cpp/arrow/SchemaField.cpp
- cpp/arrow/SchemaManifest.cpp
- csharp.test/Arrow/TestFileReader.cs
- csharp/Arrow/FileReader.cs
- csharp/Arrow/SchemaField.cs
- csharp/Arrow/SchemaManifest.cs
- csharp/ChildParquetHandle.cs
- csharp/ExceptionInfo.cs
- csharp/INativeHandle.cs
- csharp/ParquetFileReader.cs
- csharp/ParquetHandle.cs
* This allows getting a `ParquetFileReader` from an `Arrow.FileReader`, which might be required if you want to access things like the row group statistics
* In order to allow this in a safe way, I've added a new `ChildParquetHandle` class that holds a pointer to an object that is owned by some other disposable object, and added a new `INativeHandle` interface to support using either a `ParquetHandle` or `ChildParquetHandle`. There are other places in the code where we might want to use this, eg. the `RowGroupMetaData` returned from a `RowGroupReader` is one I noticed, but that should probably be a separate PR. See also #322
* Additionally, to be able to interpret the Parquet metadata when the file has a complex nested structure, expose the `SchemaManifest` associated with a `FileReader`
> Allow getting a ParquetFileReader and the SchemaManifest from an Arrow.FileReader

- .github/workflows/devcontainer.yml
The upload-artifact and download-artifact actions no longer work with duplicate artifact names. I tried testing this on my own fork but it hangs waiting for the arm64 runner, so :crossed_fingers:
The migration guide recommends this approach: https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md#multiple-uploads-to-the-same-named-artifact
> Fix devcontainer workflow after upload/download-artifact action update

- csharp.test/TestParquetFileReader.cs
- csharp/ParquetFileReader.cs
Fixes https://github.com/G-Research/ParquetSharp/issues/432
By capturing the `RandomAccessFile` in the `Free` method, we make sure that it is not collected before the `Free` method is called.
> Make sure that RandomAccessFile is not freed prematurely

- .devcontainer/Dockerfile
- .dockerignore
- .github/workflows/devcontainer.yml
- ports/re2/portfile.cmake
- ports/re2/remove_include_dir.patch
- ports/re2/vcpkg.json
- vcpkg.json
See https://github.com/google/re2/issues/488 and https://github.com/microsoft/vcpkg/issues/38064 for context
> Use a local port of re2 with a patch to work with cmake 3.29.1

- csharp/LogicalType.cs
- csharp/ParquetSharp.csproj
> Fix breaking change to LogicalTypeEnum.None value

- .github/workflows/ci.yml
- csharp/ParquetSharp.csproj
This ensures we're actually testing against the current code and haven't retrieved a previously published release from NuGet. See relevant discussion here: https://github.com/G-Research/ParquetSharp.Dataset/pull/2#discussion_r1547341071
> Add a version suffix when testing in CI

- .github/workflows/ci.yml
This PR switches our CI to use a more granular approach to vcpkg binary caching. It uses the [GitHub Actions Cache](https://learn.microsoft.com/en-us/vcpkg/consume/binary-caching-github-actions-cache) feature of vcpkg to cache individual packages instead of the all-or-nothing blob approach we were using. The huge advantage is that any package that gets properly built gets cached, even if the workflow does fail at some point in time. The other advantage is that we don't need to keep updating our cache keys to try to match the vcpkg ABI mechanism, but can instead let vcpkg do its thing.
> Use GitHub Actions for vcpkg binary caching

- .devcontainer/Dockerfile
- .github/workflows/ci.yml
- README.md
- csharp.benchmark/ParquetSharp.Benchmark.csproj
- csharp.test/ParquetSharp.Test.csproj
- fsharp.test/ParquetSharp.Test.FSharp.fsproj
- global.json
This PR updates our project files, devcontainer, and CI to use the latest .NET 8 SDK.
It also updates the macOS test targets in the CI: `macos-11` is deprecated and thus removed, `macos-14` is added and runs on Apple Silicon (aka arm64), `macos-13-xlarge` wasn't free and is replaced by `macos-13` which runs on Intel (aka x86_64) instead of Apple Silicon.
> Use net8.0 SDK

- .github/workflows/codeql-analysis.yml
The CodeQL workflow has never properly used vcpkg binary caching, even with our previous all-or-nothing approach, as `VCPKG_BINARY_SOURCES` was not set. This PR updates the workflow to follow the approach introduced in #457.
> Use vcpkg binary caching in CodeQL workflow

- .github/workflows/ci.yml
For some reason:
```
dotnet build csharp --version-suffix="something"
```
is ok, but
```
dotnet build csharp --version-suffix=""
```
fails with "Required argument missing for option: '--version-suffix'." (see https://github.com/G-Research/ParquetSharp/actions/runs/9636767326/job/26575196786)
We need to instead use:
```
dotnet build csharp --version-suffix ""
```
> Fix specifying version-suffix parameter in CI build

- .github/workflows/ci.yml
The macOS-11 environment is deprecated and will be removed on June 28th, 2024. More info here: https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/.
> ci: use `macos-12` to build the native library

- .github/workflows/check-required.yml
Inspired by this [PR](https://github.com/G-Research/fasttrackml/pull/458).
This PR improves how we create the required check "All required checks succeeded" in the following ways:
- We now use a GitHub app to create the check instead of using the token provided by GitHub Actions. This allows us to create the check run with its own check suite instead of attaching it to the first GHA check suite, which changes when a pull request is closed and reopened, or when a new run attempt is made.
- A check is created and set as queued or in_progress when the corresponding workflow run's status changes. This is needed so that the check is reset when a new run attempt is made or a PR is reopened.
- Logging is improved.
- Start/Completion times are added.
The following tasks need to be completed …
> improve check required workflow

- .github/workflows/ci.yml
Following the EOL of CentOS 7, `mirrorlist.centos.org` no longer resolves. The [pypa/manylinux](https://github.com/pypa/manylinux) 2014 image has been updated to use `vault.centos.org` instead and will likely keep up with any other changes so I suggest we switch to it for now.
> ci: use pypa/manylinux image instead of vanilla CentOS image

- cpp/Enums.cpp
- cpp/ExceptionInfo.h
- cpp/ManagedRandomAccessFile.cpp
- csharp/ArrowStatusCode.cs
- csharp/IO/ManagedRandomAccessFile.cs
- csharp/ParquetSharp.csproj
When one of the `ManagedRandomAccessFile` methods called from C++ caused an `OutOfMemoryException`, the exception message was set to `null` in `HandleException`, but this caused a `std::logic_error` on the C++ side when trying to convert `nullptr` to `std::string` when constructing an `arrow::Status` in  `ManagedRandomAccessFile::GetResult`. The error looks like:
```
ParquetSharp.ParquetException: St11logic_error (message: 'basic_string::_S_construct null not valid')
```
I've added a check for `exception == nullptr` to fix this.
I've also changed the `TRYCATCH` macro so that these errors are propagated out as an `OutOfMemoryException` again, and fixed the use of plain integers for status codes.
> Fix out of memory errors causing logic_error when using ManagedRandomAccessFile

- vcpkg.json
This PR updates the vcpkg baseline to include the fix for Thrift builds failing due to the 0.2.0 branch having been updated. The Thrift port now uses the v0.2.0 tag instead of the 0.2.0 branch ref: https://github.com/microsoft/vcpkg/issues/39786
> Update vcpkg baseline to fix incorrect Thrift hash

- csharp/DateTimeNanos.cs
- csharp/ParquetSharp.csproj
- csharp/PublicAPI/net471/PublicAPI.Shipped.txt
- csharp/PublicAPI/net6/PublicAPI.Shipped.txt
- csharp/PublicAPI/netstandard2.1/PublicAPI.Shipped.txt
This temporarily reverts #476 to allow releasing 16.1.0 from 16.1.0-beta3. I'll re-add those changes after making the 16.1.0 release.
> Promote 16.1.0-beta3 to stable release

- csharp/DateTimeNanos.cs
- csharp/PublicAPI/net471/PublicAPI.Shipped.txt
- csharp/PublicAPI/net6/PublicAPI.Shipped.txt
- csharp/PublicAPI/netstandard2.1/PublicAPI.Shipped.txt
This reapplies the changes from #476 after they were reverted for the 16.1.0 release in #477
> Add comparison operators and FromDotnetTicks to DateTimeNanos

- csharp.test/TestLogicalTypeRoundtrip.cs
- csharp/LogicalBatchReader/LogicalBatchReaderFactory.cs
Fixes #480.
When string values are required and inside an optional nested group, the group is skipped over in `LogicalBatchReaderFactory` and we only use a single `LeafReader` instance to read values. This should read null into destination rows where the enclosing group is null. But when `_nullableLeafValues` is false in the `BufferedReader`, only the non-null values would be read so we'd reach the end of the values before reaching the expected number of rows/levels.
We don't have the same problem for a required int inside an optional group for example as this is detected in `GetCompoundReader` when `typeof(TElement) != typeof(TLogical)` and is handled specially with the `OptionalReader` class.
> Fix reading required string values inside an optional group

- csharp.test/TestDecimal.cs
- csharp.test/TestDecimal128.cs
- csharp.test/TestLogicalTypeRoundtrip.cs
- csharp/Column.cs
- csharp/Decimal128.cs
- csharp/DecimalConverter.cs
- csharp/LogicalRead.cs
- csharp/LogicalTypeFactory.cs
- csharp/LogicalWrite.cs
- csharp/PublicAPI/net471/PublicAPI.Unshipped.txt
- csharp/PublicAPI/net6/PublicAPI.Unshipped.txt
- csharp/PublicAPI/netstandard2.1/PublicAPI.Unshipped.txt
- csharp/TypeUtils.cs
Fixes #252
This adds a new `DecimalConverter` class that works with arbitrary length fixed-length byte array columns (as long as values are still representable by a .NET decimal), while keeping the existing `Decimal128` class for backwards compatibility and improved performance. I've also added support for writing decimal columns backed by the int32 and int64 physical types.
> Support reading and writing decimals with arbitrary length fixed-length byte array columns and writing with int32 or int64

- .github/workflows/ci.yml
- .github/workflows/nudge.yml
The `macos-12` image we use for building has been [deprecated](https://github.com/actions/runner-images/issues/10721). This PR replaces its use by `macos-13` for building, and remove the use of `macos-12` for testing.
The `nudge` workflow configuration is also adjusted to notify us when the main CI workflow is cancelled, which was its conclusion when using a deprecated image, rather than a failure.
> Fix CI breakage following `macos-12` runner image deprecation

- .github/workflows/nudge.yml
As per the comment on https://github.com/G-Research/ParquetSharp/pull/489/files#r1912894991, 'cancelled'  value for conclusions is not supported by octo-nudge.
> Cancelled is not a valid value for a conclusion in octo-nudge

- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/nudge.yml
There is an ongoing process for reorganizing vcpkg, but it broke our CI:
- https://github.com/microsoft/vcpkg/commit/358f3893843c9d0d1b2e594183481fb68e3aa963
- https://github.com/microsoft/vcpkg-tool/pull/1553
I'm unsure how to fix it properly, but with this change, we at least make sure that we use vcpkg repo prior to the `vcpkgTools.xml` related changes and unblock our CI.
> Workaround for breaking vcpkg changes

- .github/workflows/nudge.yml
Reintroducing changes from https://github.com/G-Research/ParquetSharp/pull/489 as supports for `cancelled` conclusion is added to octo-nudge.
> Configuring nudge workflow to notify on cancelled runs

- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
Rather than checking out an older version of vcpkg, we can run bootstrap-vcpkg to update the vcpkg tools.
> Improved workaround for breaking vcpkg changes

- README.md
- csharp.test/TestPhysicalTypeRoundtrip.cs
- csharp.test/TestWriterProperties.cs
- csharp/ParquetSharp.csproj
- vcpkg.json
PR for upgrading the Arrow C++ version from 17.0.0 to 18.1.0, the latest stable version. This sets the groundwork for making the 18.1.0 ParquetSharp release, as requested by @adamreeve.
I rebuilt the project and executed the tests, which passed without problems. Please let me know if there are any extra things to consider, such as breaking changes that the tests might not have caught!
> Bump parquet-cpp-arrow to 18.1.0

- README.md
- csharp/Arrow/ArrowReaderProperties.cs
- csharp/Arrow/ArrowWriterProperties.cs
- csharp/Arrow/FileReader.cs
- csharp/Arrow/FileWriter.cs
- csharp/Column.cs
- csharp/ColumnWriter.cs
- csharp/FileDecryptionPropertiesBuilder.cs
- csharp/FileMetaData.cs
- csharp/LogicalColumnWriter.cs
- csharp/LogicalTypeFactory.cs
- csharp/ParquetFileReader.cs
- csharp/ParquetFileWriter.cs
- csharp/ReaderProperties.cs
- csharp/RowGroupReader.cs
- csharp/RowGroupWriter.cs
- csharp/WriterProperties.cs
- csharp/WriterPropertiesBuilder.cs
This PR adds a bunch of class and method descriptions for entities referenced in all the tests available at `csharp.test/Arrow`. Most of these are actually some of the core classes such as `ParquetFileReader/Writer`.
Feel free to amend any inaccuracies (I did some basic cross-referencing of existing docs/Parquet specification for these, but some might be off the mark).
Thank you!
> Documentation Improvements: Arrow API

- cpp/GroupNode.cpp
- cpp/PrimitiveNode.cpp
- csharp.test/TestNode.cs
- csharp/PublicAPI/net471/PublicAPI.Shipped.txt
- csharp/PublicAPI/net6/PublicAPI.Shipped.txt
- csharp/PublicAPI/netstandard2.1/PublicAPI.Shipped.txt
- csharp/Schema/GroupNode.cs
- csharp/Schema/PrimitiveNode.cs
There's currently no way to set the field_id when creating a new node. Ability to do this is required under some circumstances when writing Delta tables.
> Add support for setting field_id on nodes

- cpp/CMakeLists.txt
Enable control flow guard when building with msvc as ParquetSharpNative.dll is reporting [BA2008](https://github.com/microsoft/binskim/blob/main/docs/BinSkimRules.md#rule-BA2008EnableControlFlowGuard) from BinSkim.
Verified that after this change that binskim no longer reports BA2008.
More details for /guard command can be found [here](https://learn.microsoft.com/en-us/cpp/build/reference/guard-enable-control-flow-guard?view=msvc-170).
> Enable Control Flow Guard for windows builds

- .github/workflows/ci.yml
The Ubuntu 20.04 GitHub actions runner is being deprecated (https://github.com/actions/runner-images/issues/11101).
This bumps the Ubuntu version to either `ubuntu-latest` or `ubuntu-22.04`. I've used Ubuntu 22.04 for the `build-native` job rather than `ubuntu-latest` so that the arm64 library will be usable on Ubuntu 22.04 (for the x64 build we use a manylinux CentOS image for more compatibility).
> Bump version of Ubuntu used in GitHub actions

- csharp.test/TestCustomNullableType.cs
- csharp.test/TestLogicalTypeFactory.cs
- csharp.test/TestNode.cs
- csharp/ColumnDescriptor.cs
- csharp/LogicalBatchWriter/LogicalBatchWriterFactory.cs
- csharp/LogicalColumnReader.cs
- csharp/LogicalColumnWriter.cs
- csharp/LogicalTypeFactory.cs
- csharp/PublicAPI/net471/PublicAPI.Unshipped.txt
- csharp/PublicAPI/net6/PublicAPI.Unshipped.txt
- csharp/PublicAPI/netstandard2.1/PublicAPI.Unshipped.txt
- csharp/Schema/GroupNode.cs
- csharp/Schema/PrimitiveNode.cs
Fixes #525
I'm not 100% sure about this approach and whether we want to catch any discrepancies between the element type returned by `GetSystemTypes` and what the user has provided as an override. Eg. what should happen if the schema represents a list but the element type override doesn't use an array?
I also tried an alternative approach in 46eddf24ee34261b2c993c39a1fbea3645525565 that would require the user to specify whether a type can represent nulls in the `LogicalTypeFactory`.
> Support writing custom types that can represent nulls

- .github/workflows/ci.yml
Installing dotnet core 3.1 has started failing on MacOS 13 runners (image version 20250526.1184 worked but 20250602.1211 is now failing): https://github.com/G-Research/ParquetSharp/actions/runs/15455632889/job/43508150360
```
/Users/runner/work/_actions/actions/setup-dotnet/v4/externals/install-dotnet.sh: line 1440: link_types[$link_index]: unbound variable
```
Rather than try to figure out what's broken, I've updated the .NET versions used in CI as dotnet core 3.1 is out of support since December 2022. I've kept .NET 6 for now as this was an LTS version that only just went out of support in November 2024. I've also kept using 8.0 by default as this is an LTS release and 9.0 isn't, and 8.0 is what we specify in our global.json.
> Bump versions of .NET used in CI

- csharp/ColumnReader.cs
- csharp/ColumnWriter.cs
- csharp/Statistics.cs
These aren't intended to be used by users and shouldn't be possible to call directly due to these classes having internal constructors and the derived classes are all sealed. 
Partly addresses #513
> Hide docs for protected static extern members

- csharp/LogicalBatchReader/NestedReader.cs
- csharp/LogicalBatchWriter/NestedWriter.cs
- csharp/LogicalColumnReader.cs
In three places in the code base a buffer array is allocated when instead an array pool can be used instead to avoid large buffer allocation for each read/write.
> Use ArrayPool for Reader and Writer Buffers

- csharp.test/TestMemoryPool.cs
- csharp/ParquetSharp.csproj
- vcpkg.json
* Enables building Arrow with mimalloc on all x64 platforms and Linux arm64
* Enables building Arrow with jemalloc on Linux and x64 macOS
This means the default allocator will now be mimalloc, matching upstream Arrow on platforms where we enable it. Users can switch allocators with the `ARROW_DEFAULT_MEMORY_POOL` environment variable.
Mimalloc and jemalloc should work on arm64, but it appears that these don't build correctly when cross-compiling on an x64 host as part of the Arrow build. Arrow doesn't use mimalloc or jemalloc from vcpkg but always builds its own version, so this probably needs some fixes to the upstream Arrow build scripts.
> Build Arrow with support for mimalloc and jemalloc

- cpp/BufferOutputStream.cpp
- cpp/MemoryPool.cpp
- cpp/ReaderProperties.cpp
- cpp/ResizableBuffer.cpp
- cpp/WriterProperties.cpp
- cpp/WriterPropertiesBuilder.cpp
- cpp/arrow/FileReader.cpp
- cpp/arrow/FileWriter.cpp
- csharp.test/Arrow/TestFileReader.cs
- csharp.test/Arrow/TestFileWriter.cs
- csharp.test/MemoryPools.cs
- csharp.test/TestBuffer.cs
- csharp.test/TestMemoryPool.cs
- csharp.test/TestReaderProperties.cs
- csharp.test/TestWriterProperties.cs
- csharp/IO/BufferOutputStream.cs
- csharp/IO/ResizableBuffer.cs
- csharp/MemoryPool.cs
- csharp/PublicAPI.Unshipped.txt
- csharp/ReaderProperties.cs
- csharp/WriterProperties.cs
- csharp/WriterPropertiesBuilder.cs
Fixes #545
Adds new `MemoryPool` methods to get the system, Jemalloc and Mimalloc memory pools.
Allows specifying the native MemoryPool / Allocator for:
* `ResizableBuffer`
* `BufferOutputStream`
* `WriterProperties`
* `ReaderProperties`
> Allow specifying the native allocator in code

- .github/workflows/ci.yml
- csharp.test/TestMemoryPool.cs
- vcpkg.json
- use the minimum non-deprecated macOS runner to build
- avoid cross-compilation because arrow-vendored
jemalloc/mimalloc builds currently use the host architecture instead
of the target - this needs to be fixed upstream in arrow
- enable jemalloc/mimalloc for arm64 architectures
- test against all stable free runner images
note: `macos-15-intel` is used to build macOS/x64, but the build is still compatible with older versions, as seen in [this run where tests were executed on `macos-13`](https://github.com/G-Research/ParquetSharp/actions/runs/18278992855/job/52039859098).
> ci: macos-13 runners are deprecated

- .github/workflows/ci.yml
- CMakeLists.txt
- build_unix.sh
- unify Linux native build CI
- remove vcpkg caching as it is not working anymore
- limit parallelization to the amount of logical cpu cores
- remove ability to cross-compile as it is currently broken with jemalloc/mimalloc
- bump the minimum required version of cmake to align with vcpkg
> CI: build Linux arm64 for a CentOS 7 container too
